#!/bin/bash


# HERE IT WILL LISTEN ON LINUX SOCKET 
service mariadb start
sleep 10

# 
mariadb -e "CREATE DATABASE IF NOT EXISTS  $MYSQL_DATABASE;"
mariadb -e "CREATE USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';"
mariadb -e "GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';"
mariadb -e "FLUSH PRIVILEGES;"

# HERE WILL SHUT IT DOWN AND RUN IT SAFELY IN A SPECIFIC PORT AND DEFAULT IP
mariadb-admin shutdown
exec mariadbd-safe --port=3306 --bind-address=0.0.0.0